version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: etl-dashboard-backend:latest
    container_name: etl-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
      - ./.env.production:/app/.env
    environment:
      - PYTHONPATH=/app
      - ENV=production
    networks:
      - etl-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: etl-dashboard-frontend:latest
    container_name: etl-frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app/frontend
      - ./data:/app/data
      - ./.env.production:/app/.env
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    depends_on:
      - backend
    networks:
      - etl-network
    restart: unless-stopped

networks:
  etl-network:
    driver: bridge
    name: etl-dashboard-network

volumes:
  etl-data:
    driver: local