version: '3.8'

services:
  backend:
    image: etl_dashboard-backend:latest
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - FASTAPI_RELOAD=false
      - LOG_LEVEL=INFO
      - UPLOAD_FOLDER=/app/data/uploads
      - PROCESSED_FOLDER=/app/data/processed
    volumes:
      - etl_data:/app/data
    networks:
      - etl-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: etl_dashboard-frontend:latest
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: ingress
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=false
      - FASTAPI_HOST=backend
      - FASTAPI_PORT=8000
    volumes:
      - etl_data:/app/data
    networks:
      - etl-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  etl-network:
    driver: overlay
    attachable: true

volumes:
  etl_data:
    driver: local