services:
  - type: web
    name: etl-dashboard
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free  # Can upgrade to 'starter' or 'standard' for production
    healthCheckPath: /health
    buildCommand: ""  # Docker build handled automatically
    startCommand: ""  # Uses CMD from Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /app
      - key: FLASK_ENV
        value: production
      - key: ENV
        value: production
      - key: BACKEND_URL
        value: http://localhost:8000
      - key: FLASK_DEBUG
        value: false
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - requirements.txt
        - Dockerfile.render
        - .env.production
        - setup.py
        - run_simple.py
      ignoredPaths:
        - docs/**
        - tests/**
        - data/uploads/**
        - "*.md"
        - ".git/**"
    autoDeploy: true  # Auto-deploy on git push
    region: oregon  # Choose: oregon, frankfurt, singapore
    rootDir: .  # Root directory of the repository
    
# Optional: Add a database service if needed
# databases:
#   - name: etl-database
#     plan: free  # PostgreSQL free tier
#     databaseName: etl_dashboard
#     user: etl_user